// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiWb0teVRQJdBJ8FUaFS7S2tLx1vGcqOU',
    appId: '1:959386847228:web:8f2d8303dad2233c0a1479',
    messagingSenderId: '959386847228',
    projectId: 'ngay1407-demo',
    authDomain: 'ngay1407-demo.firebaseapp.com',
    storageBucket: 'ngay1407-demo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlwEZYWGvdsmkbr8Ho2l0Usc36G3DxPNc',
    appId: '1:959386847228:android:008934fc605090b60a1479',
    messagingSenderId: '959386847228',
    projectId: 'ngay1407-demo',
    databaseURL: 'https://ngay1407-demo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ngay1407-demo.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZFdnjsOYkZ-h2DK3JUjGR0ANHCj9IWz4',
    appId: '1:959386847228:ios:d804fe659f1871ff0a1479',
    messagingSenderId: '959386847228',
    projectId: 'ngay1407-demo',
    storageBucket: 'ngay1407-demo.firebasestorage.app',
    iosBundleId: 'com.example.ngay1507',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZFdnjsOYkZ-h2DK3JUjGR0ANHCj9IWz4',
    appId: '1:959386847228:ios:d804fe659f1871ff0a1479',
    messagingSenderId: '959386847228',
    projectId: 'ngay1407-demo',
    storageBucket: 'ngay1407-demo.firebasestorage.app',
    iosBundleId: 'com.example.ngay1507',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiWb0teVRQJdBJ8FUaFS7S2tLx1vGcqOU',
    appId: '1:959386847228:web:12e213032bcc57ae0a1479',
    messagingSenderId: '959386847228',
    projectId: 'ngay1407-demo',
    authDomain: 'ngay1407-demo.firebaseapp.com',
    storageBucket: 'ngay1407-demo.firebasestorage.app',
  );
}
