// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQNyj5Xr36K0G5NCM42F7pNtpURZteZ8o',
    appId: '1:72538885033:web:afb5767878ddf1dba652b8',
    messagingSenderId: '72538885033',
    projectId: 'mybookshelf-f15e0',
    authDomain: 'mybookshelf-f15e0.firebaseapp.com',
    databaseURL: 'https://mybookshelf-f15e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mybookshelf-f15e0.firebasestorage.app',
    measurementId: 'G-H14PTK0YNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1A6-SAtBPa4p8Cg_Y2jY4M3oCK2bC77o',
    appId: '1:72538885033:android:8fe55fe82f46b1aca652b8',
    messagingSenderId: '72538885033',
    projectId: 'mybookshelf-f15e0',
    databaseURL: 'https://mybookshelf-f15e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mybookshelf-f15e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAWBNLdMsTkVpyNvnpoamSZ5ePy0ZCZKA',
    appId: '1:72538885033:ios:70a2f7e496a34ec8a652b8',
    messagingSenderId: '72538885033',
    projectId: 'mybookshelf-f15e0',
    databaseURL: 'https://mybookshelf-f15e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mybookshelf-f15e0.firebasestorage.app',
    iosBundleId: 'com.example.ngay2107',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAWBNLdMsTkVpyNvnpoamSZ5ePy0ZCZKA',
    appId: '1:72538885033:ios:70a2f7e496a34ec8a652b8',
    messagingSenderId: '72538885033',
    projectId: 'mybookshelf-f15e0',
    databaseURL: 'https://mybookshelf-f15e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mybookshelf-f15e0.firebasestorage.app',
    iosBundleId: 'com.example.ngay2107',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQNyj5Xr36K0G5NCM42F7pNtpURZteZ8o',
    appId: '1:72538885033:web:e565835bd4868a32a652b8',
    messagingSenderId: '72538885033',
    projectId: 'mybookshelf-f15e0',
    authDomain: 'mybookshelf-f15e0.firebaseapp.com',
    databaseURL: 'https://mybookshelf-f15e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mybookshelf-f15e0.firebasestorage.app',
    measurementId: 'G-S3NZ13DC50',
  );
}
