// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUEzr0rWiEsHElq6zKcVjqQ742SQ7LB_I',
    appId: '1:240213824111:web:3ae55e3666f5e44643b39a',
    messagingSenderId: '240213824111',
    projectId: 'meowcollector-427ce',
    authDomain: 'meowcollector-427ce.firebaseapp.com',
    storageBucket: 'meowcollector-427ce.firebasestorage.app',
    measurementId: 'G-KWBRWNB4N5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxe9AY8_mjsBg4Qi3SN8WDaxwjMb7shhE',
    appId: '1:240213824111:android:05f9d058337c34f543b39a',
    messagingSenderId: '240213824111',
    projectId: 'meowcollector-427ce',
    storageBucket: 'meowcollector-427ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAzMu82Pi1tnPrK7o0WjQjmYHgtTEzhrg',
    appId: '1:240213824111:ios:4c6b8c9dc4a054b243b39a',
    messagingSenderId: '240213824111',
    projectId: 'meowcollector-427ce',
    storageBucket: 'meowcollector-427ce.firebasestorage.app',
    iosBundleId: 'com.example.meowCollector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAzMu82Pi1tnPrK7o0WjQjmYHgtTEzhrg',
    appId: '1:240213824111:ios:4c6b8c9dc4a054b243b39a',
    messagingSenderId: '240213824111',
    projectId: 'meowcollector-427ce',
    storageBucket: 'meowcollector-427ce.firebasestorage.app',
    iosBundleId: 'com.example.meowCollector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUEzr0rWiEsHElq6zKcVjqQ742SQ7LB_I',
    appId: '1:240213824111:web:9926a0507148153443b39a',
    messagingSenderId: '240213824111',
    projectId: 'meowcollector-427ce',
    authDomain: 'meowcollector-427ce.firebaseapp.com',
    storageBucket: 'meowcollector-427ce.firebasestorage.app',
    measurementId: 'G-27SRHVHD75',
  );
}
