// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3AuNH4FaBR2ju8CKmorcjLOW-M7S6AHY',
    appId: '1:53351145953:web:548e84e49099f602b3f2a0',
    messagingSenderId: '53351145953',
    projectId: 'pushnotification-d4297',
    authDomain: 'pushnotification-d4297.firebaseapp.com',
    storageBucket: 'pushnotification-d4297.firebasestorage.app',
    measurementId: 'G-QB03ZRG38R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByUoK7LUlRiAFImxyLdcG1fWRABwmgp4o',
    appId: '1:53351145953:android:051c56b06aa9bafdb3f2a0',
    messagingSenderId: '53351145953',
    projectId: 'pushnotification-d4297',
    storageBucket: 'pushnotification-d4297.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBADb9tETnZlRqgF1pAKxCwDToLclcIUDg',
    appId: '1:53351145953:ios:00f310727442180cb3f2a0',
    messagingSenderId: '53351145953',
    projectId: 'pushnotification-d4297',
    storageBucket: 'pushnotification-d4297.firebasestorage.app',
    iosBundleId: 'com.example.ngay2707',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBADb9tETnZlRqgF1pAKxCwDToLclcIUDg',
    appId: '1:53351145953:ios:00f310727442180cb3f2a0',
    messagingSenderId: '53351145953',
    projectId: 'pushnotification-d4297',
    storageBucket: 'pushnotification-d4297.firebasestorage.app',
    iosBundleId: 'com.example.ngay2707',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3AuNH4FaBR2ju8CKmorcjLOW-M7S6AHY',
    appId: '1:53351145953:web:dc49854290dee316b3f2a0',
    messagingSenderId: '53351145953',
    projectId: 'pushnotification-d4297',
    authDomain: 'pushnotification-d4297.firebaseapp.com',
    storageBucket: 'pushnotification-d4297.firebasestorage.app',
    measurementId: 'G-M4N3KXQEJX',
  );
}
