// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx9W6quDG1VDvL1rlFE7grakvj3nLrECw',
    appId: '1:174259457290:web:6cb5e2032e6d8f0a28fef3',
    messagingSenderId: '174259457290',
    projectId: 'recipeify-226c9',
    authDomain: 'recipeify-226c9.firebaseapp.com',
    databaseURL: 'https://recipeify-226c9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'recipeify-226c9.firebasestorage.app',
    measurementId: 'G-1W2EDCB2CS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWR4nwU9LmcGRY8rOQlP14ewiDckBIZN8',
    appId: '1:174259457290:android:9174ed93b5662e8828fef3',
    messagingSenderId: '174259457290',
    projectId: 'recipeify-226c9',
    databaseURL: 'https://recipeify-226c9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'recipeify-226c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBInAmFVbyxfOwO6exifLdZtRYzPjaFfqM',
    appId: '1:174259457290:ios:64c27a655a24368628fef3',
    messagingSenderId: '174259457290',
    projectId: 'recipeify-226c9',
    databaseURL: 'https://recipeify-226c9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'recipeify-226c9.firebasestorage.app',
    iosBundleId: 'com.example.recipeify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBInAmFVbyxfOwO6exifLdZtRYzPjaFfqM',
    appId: '1:174259457290:ios:64c27a655a24368628fef3',
    messagingSenderId: '174259457290',
    projectId: 'recipeify-226c9',
    databaseURL: 'https://recipeify-226c9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'recipeify-226c9.firebasestorage.app',
    iosBundleId: 'com.example.recipeify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx9W6quDG1VDvL1rlFE7grakvj3nLrECw',
    appId: '1:174259457290:web:48dc1832b0db6d1028fef3',
    messagingSenderId: '174259457290',
    projectId: 'recipeify-226c9',
    authDomain: 'recipeify-226c9.firebaseapp.com',
    databaseURL: 'https://recipeify-226c9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'recipeify-226c9.firebasestorage.app',
    measurementId: 'G-47TVF35QJ9',
  );
}
